# Generated by Django 5.2.17 on 2026-09-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('CO', 'Cosméticos'), ('DM', 'Dispositivos Médicos'), ('AL', 'Alimentos'), ('VE', 'Veterinarios')], max_length=2)),
                ('codigo_tramite', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('valor_uf', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
