# Generated by Django 5.2.17 on 2026-09-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cliente', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('tramite', models.CharField(max_length=100)),
                ('borrador_cotizacion', models.TextField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('CO', 'Cosméticos'), ('DM', 'Dispositivos Médicos'), ('AL', 'Alimentos')], max_length=2),
        ),
    ]
